<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        try {
            console.log("En el try se agrega el codigo a evaluar")
            noExiste;
            
        } catch (error) {
            console.log("Catch captura cualquier error surgido o lanzado en el try");
            console.log(error);

        }finally{
            console.log("El bloque finally se ejecutará siempre al final de un bloque try-catch");
        }

        //Manejo de error personalizado:
        try{
            let numero = 10;
            if(isNaN(numero)){
                throw new Error("El caractér introducido no es un Número");
            }

        }catch (error){
            console.log(`Se produjo el siguiente error: ${error}`);

        }

    </script>
</body>
</html>